redis:
  image: redis:2
  ports:
      - "6379"
  volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data

watchmen_web:
  build: ./
  container_name: watchmen_web
  ports:
      - "3000:3000"
  links:
      - redis
  command: node run-web-server.js
  env_file: docker-compose.env

watchmen_server:
  build: ./
  container_name: watchmen_srv
  links:
      - redis
  command: node run-monitor-server.js
  env_file: docker-compose.env
