redis:
  container_name: watchmen_redis
  image: redis:2
  ports:
      - "6379"
  volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data

watchmen_populate:
    # populates with stub data of real services
    build: ./
    container_name: watchmen_populate
    links:
        - redis
    volumes:
        - ./test/fixtures/real-services.js:/watchmen/test/fixtures/real-services.js
    command: node scripts/data-load/populate-services-from-fixtures.js -r -e production
    env_file: docker-compose.env

watchmenweb:
    build: ./
    container_name: watchmen_web
    volumes:
        - ./webserver/routes/web-auth-route.js:/watchmen/webserver/routes/web-auth-route.js
    ports:
        - "3000:3000"
    links:
        - redis
    command: node run-web-server.js
    env_file: docker-compose.env

watchmenserver:
    build: ./
    container_name: watchmen_srv
    links:
        - redis
    command: node run-monitor-server.js
    env_file: docker-compose.env
